### ISSUE TITLE
Absturz bei Spielstart - "Live" Fenster

### ISSUE THREAD

**Issue by moritz-lgstr** [LarsG21/Darts_Project#5]
Woran kann es liegen dass das Programm jedesmal abstürzt nachdem ich das Default Image gesetzt habe und dann auf Start drücke? Dann kommt die Live Kamera und die zeigt nichts an danach dauert es kurz und das "Live" Fenster zeigt keine Reaktion mehr und dann schließt sich alles

**Comment by LarsG21** [comment]
Hey,
Das kann eventuell daran liegen, dass die falsche Nummer bei der Kamera ausgewählt ist. Oder dass er die Kamera nicht auslesen kann. Wird denn keine Fehlermeldung angezeigt?

**Comment by moritz-lgstr** [comment]
Set default image
Set default image
Set default image
Set default image
Set default image
Set default image
Set default image
LEN: 0
Traceback (most recent call last):
  File "c:\Users\User\Downloads\download\darts\main_with_gui.py", line 256, in run
    ret = detect_dart_circle_and_set_limits(img_roi=img_roi)
  File "c:\Users\User\Downloads\download\darts\main_with_gui.py", line 103, in detect_dart_circle_and_set_limits
    imgContours, contours, imgCanny = ContourUtils.get_contours(img=img_roi, cThr=(cannyLow, cannyHigh),
  File "c:\Users\User\Downloads\download\darts\ContourUtils.py", line 67, in get_contours
    cv2.destroyWindow("Gauss")
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:1261: error: (-27:Null pointer) NULL window: 'Gauss' in function 'cvDestroyWindow'


Dass ist das einzige was kommt, konnte aber nicht recht was damit anfangen🤔

**Comment by LarsG21** [comment]
Ich verwende zum debuggen zusätzliche Fenster in OpenCV. Eins davon ist "Gauss". Anscheinend versucht er das zu schließen, obwohl es nicht geöffnet ist. 
Versuch mal Zeile 67 mit dem hier zu ersetzen:
if cv2.getWindowProperty("Gauss", cv2.WND_PROP_VISIBLE) >= 0:
    cv2.destroyWindow("Gauss")
else:
    print("Window 'Gauss' not found.")
Oder du kommentierst es einfach mal aus.
